server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Não cachear index.html e service worker
    location ~* (index\.html|flutter_service_worker\.js)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        expires 0;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
}
